apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    resources:
      limits:
        memory: "32Mi"  # Increase this value based on your analysis
      requests:
        memory: "16Mi"
