apiVersion: v1

kind: ReplicationController

metadata:
  name: my-app-replica
  labels:
    app: myapp
    tier: front_end

spec:
  template:
    metadata:
      name: my-app-pod
      labels:
        app: my-app
        tier: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx

  replicas: 3