apiVersion: v1
kind: Pod
metadata:
  name: taint-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
  tolerations:
  - key: "special"
    operator: "Equal"
    value: "high-memory"
    effect: "NoSchedule"
