apiVersion: apps/v1
kind: Deployment
metadata:
  name: extra-deployment
  namespace: ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extra
  template:
    metadata:
      labels:
        app: extra
    spec:
      containers:
      - name: extra
        image: busybox
        ports:
        - containerPort: 80
